name: entra_auth_mobile
description: A Flutter mobile app with Azure Entra ID authentication

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # MSAL for authentication
  msal_flutter: ^2.0.0
  
  # HTTP client
  http: ^1.2.1
  
  # State management
  provider: ^6.1.2
  
  # Secure storage for tokens
  flutter_secure_storage: ^9.2.2
  
  # UI components
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true